### ISSUE TITLE
[Crash]  2.0.1 not working with 1.20.1 ~ Fabric

### ISSUE THREAD

**Issue by xR4YM0ND** [mineblock11/Armorful#11]
I tried to run Armorful 2.0.1 on 1.20.1 but it doesnt load
( On Modrinth its tagged with 1.20.1 )

[latest.log](https://gist.github.com/xR4YM0ND/e808e067a7bc11431ebc181d3104b428)

**Comment by mineblock11** [comment]
Modify the fabric.mod.json, ill release a hotfix later.

**Comment by xR4YM0ND** [comment]
When does the hotfix come?
