### ISSUE TITLE
[Crash] Strange crash during the creation of a new world (possibly related to C2ME?)

### ISSUE THREAD

**Issue by vico93** [mineblock11/Armorful#7]
After installing Armorful, i got this weird crash when trying to generate a new world. At first seems to be related to C2ME, but since in the crash it states that it could be related to another mod and there is some references to Armorful on the classes affected, i posted this here as well to be safe.

Crash report: [GIST](https://gist.github.com/vico93/8fe824e44bb75b8322c8b1107665a34c)

**Comment by vico93** [comment]
> Armorful doesn't do anything with feature placements. This is a CM2E issue

Meanwhile @ishland said on the other thread: "This is caused by Armorful attempting to generate loot tables for drowned during structure spawning on worldgen threads and this should be avoided."

**Comment by mineblock11** [comment]
This is done anyways by vanilla already?

**Comment by ishland** [comment]
> This is done anyways by vanilla already?

Vanilla doesn't use loot tables on entity creation and loots for chests are generated only when they are first opened.

**Comment by Estrelaura** [comment]
Happening a lot on a server i manage, not even related to C2ME, since i uninstalled. It just takes someone trying to generate a chunk with an ocean ruin on it and it happens (because of the drowned) 
[crash-2023-09-12_19.40.39-server.txt](https://github.com/mineblock11/Armorful/files/12615207/crash-2023-09-12_19.40.39-server.txt)

**Comment by vico93** [comment]
Strange how @mineblock11 closed #14 telling to update C2ME even after @ishland already stated that this is caused by bad practices on mineblock's side.

I just removed Armorful from my pack until this issue is properly fixed.

**Comment by mineblock11** [comment]
I currently dont have time to fix this. I have been unable to reproduce this with the latest C2ME versions.

**Comment by Trent2087** [comment]
This is still an issue
https://hastebin.com/share/lalobolate.yaml

**Comment by mineblock11** [comment]
![](https://media.tenor.com/T6fSt9T6DLEAAAAC/tkkra-ugh.gif)
